# 包含 Flutter 默认的 lint 规则
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 不强制使用 const 构造函数
    prefer_const_constructors: false
    # 不强制使用 final 字段，这个是在继承父类时，父类中是final，子类中是var，所以需要关闭
    prefer_final_fields: false
    # 不强制在 Widget 构造函数中使用 key 参数
    use_key_in_widget_constructors: false
    # 不强制使用 const 字面量创建不可变列表
    prefer_const_literals_to_create_immutables: false
    # 不强制使用 const 构造函数创建不可变对象
    prefer_const_constructors_in_immutables: false
    # 允许使用 print 语句
    avoid_print: false
    